### ISSUE TITLE
Data for detailed analysis in NEE paper

### ISSUE THREAD

**Issue by EnvGenomics** [Djeppschmidt/GLUSEEN#1]
Hi,sorry to interrupt. I wanted to reproduce the results of your paper but no taxonomic information and original OTU table was found in the data folder, which makes the process cumbersome. Is that ok that you offer me the above detailed information?

**Comment by Djeppschmidt** [comment]
No problem! I've uploaded a zip file in the GithubFiles folder called TaxonomyAssignments.zip. It contains a number of files, including the original OTU tables, and files for the taxonomy assignments. Because many of the files that I put on github have the OTU's in a similar format as required for PCORD (taxa: o1, o2 ...), I included directories that include excel files that have keys that should allow you to decode/replicate the analyses. For the 16s, this includes the files I used to filter the archaea and bacteria into distinct communities. The taxonomy assignment files should allow you to assign the denovo IDs. I hope this helps! Let me know if you need anything else, or if anything is confusing
